name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test primes
      id: test-primes
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test primes
        setup-command: ''
        command: make test
        timeout: 3
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-PRIMES_RESULTS: "${{steps.test-primes.outputs.result}}"
      with:
        runners: test-primes
